export const themeConfig = {
  typography: {
    '--font-primary': 'var(--font-open-sans)',
  },
  colors: {
    light: {
      '--text-color-primary': 'var(--text-neutral-900)',
      '--text-color-accent': 'var(--text-green-600)',
      '--background-color-secondary': 'var(--bg-neutral-100)',
      '--background-color-tertiary': 'var(--bg-neutral-300)',
      '--border-color-accent': 'var(--border-green-600)',
      '--border-color-primary': 'var(--border-neutral-200)',
      '--border-color-tertiary': 'var(--border-green-700)',
      '--button-background-color-primary': 'var(--bg-green-600)',
      '--button-background-color-secondary': 'var(--bg-white)',
      '--button-background-color-secondary-hover': 'var(--bg-neutral-100)',
      '--button-border-color-secondary': 'var(--border-neutral-200)',
      '--button-text-color-secondary': 'var(--text-neutral-900)',
      '--chat-button-border-color-gradientThree': 'var(--border-green-700)',
      '--chat-button-border-color-gradientFour': 'var(--border-green-600)',
      '--chat-button-background-color-gradientOne': 'var(--bg-green-600)',
      '--chat-button-background-color-gradientTwo': 'var(--bg-green-300)',
    },
    dark: {
      '--text-color-primary': 'var(--text-neutral-100)',
      '--text-color-accent': 'var(--text-green-400)',
      '--background-color-secondary': 'var(--bg-neutral-950)',
      '--background-color-tertiary': 'var(--bg-neutral-900)',
      '--border-color-accent': 'var(--border-green-400)',
      '--border-color-primary': 'var(--border-neutral-900)',
      '--border-color-tertiary': 'var(--border-green-300)',
      '--button-background-color-primary': 'var(--bg-green-600)',
      '--button-background-color-secondary': 'var(--bg-neutral-900)',
      '--button-background-color-secondary-hover': 'var(--bg-neutral-800)',
      '--button-border-color-secondary': 'var(--border-neutral-900)',
      '--button-text-color-secondary': 'var(--text-neutral-200)',
      '--chat-button-border-color-gradientThree': 'var(--border-green-400)',
      '--chat-button-border-color-gradientFour': 'var(--border-green-700)',
      '--chat-button-background-color-gradientOne': 'var(--bg-green-400)',
      '--chat-button-background-color-gradientTwo': 'var(--bg-green-800)',
    },
  },
};
