packages:
  - packages/*
  - apps/*

catalog:
  '@types/node': 22.17.0
  '@types/react': ^19.1.12
  classnames: ~2.5.1
  cross-env: ^10.0.0
  react: ^19.1.1
  tailwindcss: ~4.0.17
  typescript: 5.8.3

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
