packages:
  - packages/*
  - apps/*

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  '@types/node': ^24.10.1
  '@types/react': ^19.2.15
  classnames: ~2.5.1
  cross-env: ^10.0.0
  react: ^19.2.6
  tailwindcss: ~4.1.17
  typescript: 5.9.3
