packages:
  - packages/*
  - apps/*

catalog:
  '@types/node': ^24.10.1
  '@types/react': ^19.2.13
  classnames: ~2.5.1
  cross-env: ^10.0.0
  react: ^19.2.4
  tailwindcss: ~4.1.17
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@nodejs/doc-kit'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - rclone.js
  - sharp
  - unrs-resolver
  - workerd
