packages:
  - packages/*
  - apps/*

# https://pnpm.io/settings#onlybuiltdependencies
# These are the dependencies that we trust to safely
# run installation scripts.
onlyBuiltDependencies:
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
