name: Suggest a new feature or improvement for the Node.js Website
description: 'Do you have an idea or a suggestion and you want to share?'
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea how to improve the site? That's awesome!
        Before submitting, please have a look at the existing issues if there's already
        something related to your suggestion.
  - type: textarea
    attributes:
      label: 'Enter your suggestions in details:'
      placeholder: |
        1. What I expected to happen.
        2. Your reason (if possible, images or videos are welcome).
        3. What I plan to do (Optional but better).
    validations:
      required: true
