pipeline {
    agent none

    stages {
        stage('Hello') {
            agent any
            steps {
                //sh 'docker volume rm vol-in'
                sh 'docker volume create vol-in'
                sh 'docker volume create vol-out' //wrzucac do katalogu oznacznego tagiem
                sh 'rm * -r'
                sh 'docker volume ls'
    
                sh 'docker run -d --rm --name dummy -v vol-in:/va alpine tail -f /dev/null'
                sh 'docker cp . dummy:/vi'
                sh 'docker stop dummy'
            }
            
        }
        
        stage('Build') {
            agent {
                docker { 
                    image 'node' 
                    args '-v vol-in:/va -v vol-out:/vo'
                    
                }
            }
            steps {
                sh 'cp /va/* . -r'
                sh 'ls'
                sh 'npm install --save --legacy-peer-deps'
                sh 'npm run build'
                sh 'touch aaa'
                sh 'cp aaa /va'
            }
        }
        
    }
}
