node {
    def app

    stage('Clone repository') {
        checkout scm CI

    //    sh 'docker volume create vol-in'
    //    sh 'docker volume create vol-out'
    //    sh 'docker volume ls'

    //    sh 'docker run -d --rm --name dummy -v vol-in:/vi alpine tail -f /dev/null'
    //    sh 'docker cp . dummy:/vi'
    //    sh 'docker stop dummy'
    }

    stage('Dependency image') {
    checkout scm CI

    docker.build("dependency-image", "./CI/dependencies")
    }

    stage('Build image') {
       app = docker.build("build-image", "./CI/build")
    }

    stage('Test image') {
        docker.build("test-image", "./CI/test")
        // app.inside {
        //     sh 'echo "Tests passed"'
        // }
    }

    stage('Deploy image') {
        docker.build("deploy-image", "./CI/deploy")
    }

    stage('Publish image') {
        
    }
}