'use strict'

module.exports = {
  EG: 'Africa',
  KE: 'Africa',
  MA: 'Africa',
  MU: 'Africa',
  NG: 'Africa',
  ZA: 'Africa',
  AE: 'Asia',
  BD: 'Asia',
  CN: 'Asia',
  HK: 'Asia',
  ID: 'Asia',
  IL: 'Asia',
  IN: 'Asia',
  LB: 'Asia',
  JP: 'Asia',
  KR: 'Asia',
  LK: 'Asia',
  MY: 'Asia',
  NP: 'Asia',
  PH: 'Asia',
  RU: 'Asia',
  SA: 'Asia',
  TH: 'Asia',
  TW: 'Asia',
  VN: 'Asia',
  AT: 'Europe',
  BA: 'Europe',
  BE: 'Europe',
  BG: 'Europe',
  BY: 'Europe',
  CH: 'Europe',
  CZ: 'Europe',
  DE: 'Europe',
  DK: 'Europe',
  EE: 'Europe',
  ES: 'Europe',
  FI: 'Europe',
  FR: 'Europe',
  GB: 'Europe',
  GH: 'Europe',
  GR: 'Europe',
  HR: 'Europe',
  HU: 'Europe',
  IE: 'Europe',
  IS: 'Europe',
  IT: 'Europe',
  LT: 'Europe',
  LU: 'Europe',
  ME: 'Europe',
  MK: 'Europe',
  MT: 'Europe',
  NL: 'Europe',
  NO: 'Europe',
  PL: 'Europe',
  PT: 'Europe',
  RO: 'Europe',
  RS: 'Europe',
  SE: 'Europe',
  SI: 'Europe',
  SK: 'Europe',
  TR: 'Europe',
  UA: 'Europe',
  CA: 'North America',
  GP: 'North America',
  US: 'North America',
  AR: 'Latin America',
  BO: 'Latin America',
  BR: 'Latin America',
  CL: 'Latin America',
  CO: 'Latin America',
  CR: 'Latin America',
  DO: 'Latin America',
  EC: 'Latin America',
  GT: 'Latin America',
  MX: 'Latin America',
  PA: 'Latin America',
  PE: 'Latin America',
  UY: 'Latin America',
  VE: 'Latin America',
  AU: 'South Pacific',
  NZ: 'South Pacific',
  SG: 'South Pacific'
}
