#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

DIR=$(cd `dirname $0` && pwd -P)

# adds these changes to be part of the current commit
git checkout $DIR/../public/node-releases-data.json
git checkout $DIR/../public/blog-posts-data.json

# lint and format staged files
npx lint-staged
