import { readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { defineRule } from '../rule.mjs';
import { collectAnchors, loadAnchors } from '../utils/headings.mjs';

/**
 * @typedef Options
 * @property {Array<string> | string} basePaths
 *   Directories that root-relative links (`/about`) resolve against, in
 *   order. Route targets need no extension; directories resolve to `index.*`.
 * @property {Array<string> | string} ignoreFiles
 *   Globs of files (relative to `cwd`) not to check.
 * @property {Array<string> | string} ignoreLinks
 *   Globs of link paths not to check.
 * @property {'self' | 'all' | false} fragments
 *   Which `#fragment`s to verify: those pointing at the current document,
 *   all of them (parsing the target documents), or none.
 * @property {'doc-kit' | 'github'} slugger
 *   How heading anchors are generated by the site the links point at.
 */

const MARKDOWN = new Set(['.md', '.mdx', '.markdown']);
const urlBase = new URL('https://nodejs.org');

/** @type {Map<string, Promise<Map<string, string>>>} */
const directoryCache = new Map();

const decode = value => {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
};

/**
 * @param {string} value
 * @param {string} basePath
 */
const getUrlParts = (value, basePath) => {
  try {
    const url = new URL(value, pathToFileURL(basePath));

    if (url.protocol !== 'file:' || url.host) {
      return undefined;
    }

    return {
      hash: decode(url.hash.slice(1)),
      // Not resolved against the file, so `/route` is not prefixed by the cwd
      pathname: decode(new URL(value, urlBase).pathname),
      rootRelative: value.startsWith('/'),
      targetPath: fileURLToPath(url),
    };
  } catch {
    return undefined;
  }
};

/**
 * Lists a directory once, mapping both names and extensionless stems to the
 * file they resolve to.
 *
 * @param {string} directory
 */
const readDirectory = directory => {
  if (!directoryCache.has(directory)) {
    directoryCache.set(
      directory,
      readdir(directory, { withFileTypes: true }).then(
        items => {
          const files = items
            .filter(item => item.isFile())
            .map(item => item.name);
          const result = new Map(files.map(name => [name, name]));

          for (const name of files) {
            const extension = path.extname(name);
            const stem = extension && name.slice(0, -extension.length);

            if (stem && !result.has(stem)) {
              result.set(stem, name);
            }
          }

          return result;
        },
        () => new Map()
      )
    );
  }

  return directoryCache.get(directory);
};

/**
 * @param {string} target
 */
const isDirectory = target =>
  stat(target).then(
    stats => stats.isDirectory(),
    () => false
  );

/**
 * @param {string} target
 */
const resolveFile = async target => {
  const directory = path.dirname(target);
  const file = (await readDirectory(directory)).get(path.basename(target));

  if (file) {
    return path.join(directory, file);
  }

  const index = (await readDirectory(target)).get('index');

  return index && path.join(target, index);
};

export default defineRule({
  name: 'link-targets',
  description:
    'Local links point at existing files, and fragments at existing headings',
  defaults: {
    basePaths: ['.'],
    ignoreFiles: [],
    ignoreLinks: [],
    fragments: 'self',
    slugger: 'doc-kit',
  },
  /** @param {Options} options */
  async run(context, options, file) {
    const basePaths = [options.basePaths].flat();
    const ignoredFiles = [options.ignoreFiles].flat();
    const ignoredLinks = [options.ignoreLinks].flat();
    const cwd = path.resolve(file.cwd || process.cwd());
    const currentPath = file.path && path.resolve(cwd, file.path);

    if (
      currentPath &&
      ignoredFiles.some(pattern =>
        path.matchesGlob(path.relative(cwd, currentPath), pattern)
      )
    ) {
      return;
    }

    const basePath = currentPath || path.join(cwd, 'index');
    const targets = [];

    for (const { node } of [
      ...context.links,
      ...context.definitions,
      ...context.images,
    ]) {
      if (!node.url) {
        continue;
      }

      const parts = getUrlParts(node.url, basePath);

      if (
        parts &&
        !ignoredLinks.some(pattern => path.matchesGlob(parts.pathname, pattern))
      ) {
        targets.push([node, parts]);
      }
    }

    let selfAnchors;

    for (const [node, parts] of targets) {
      const candidates = parts.rootRelative
        ? basePaths.map(base => path.join(cwd, base, parts.pathname))
        : [parts.targetPath];

      let match;

      for (const candidate of candidates) {
        match =
          candidate === currentPath
            ? currentPath
            : await resolveFile(candidate);

        if (match) {
          break;
        }
      }

      if (!match) {
        // A relative link to a directory (`./status`) lists it on GitHub
        if (!parts.rootRelative && (await isDirectory(parts.targetPath))) {
          continue;
        }

        file.message(`Cannot find file for link \`${node.url}\``, node);
        continue;
      }

      const isImage = node.type === 'image' || node.type === 'imageReference';

      if (isImage || !parts.hash || !options.fragments) {
        continue;
      }

      if (match === currentPath) {
        selfAnchors ??= collectAnchors(context.tree, options.slugger);

        if (!selfAnchors.has(parts.hash)) {
          file.message(`Cannot find heading for \`#${parts.hash}\``, node);
        }
      } else if (
        options.fragments === 'all' &&
        MARKDOWN.has(path.extname(match).toLowerCase())
      ) {
        const anchors = await loadAnchors(match, options.slugger);

        if (!anchors.has(parts.hash)) {
          file.message(
            `Cannot find heading for \`#${parts.hash}\` in \`${path.relative(path.dirname(basePath), match)}\``,
            node
          );
        }
      }
    }
  },
});
