name: Auto-merge PRs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  auto-merge:
    name: Auto-merge
    if: github.repository == 'nodejs/nodejs.org'
    runs-on: ubuntu-latest
    permissions:
      # Required to approve and merge pull requests
      pull-requests: write
      # Required to merge pull requests via merge queue
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: nodejs/web-team/actions/auto-merge-prs@b087df186d25f8792fb85cc7794f68718726b8ee
        with:
          merge-method: queue
