name: Find inactive collaborators

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 UTC on the 1st day of every month

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  find:
    if: github.repository == 'nodejs/nodejs.org'
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Report inactive collaborators
        id: inactive
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { default: report } = await import("${{github.workspace}}/.github/scripts/report-inactive-collaborators.mjs");
            report(github, context);
