name: Find inactive collaborators

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 UTC on the 1st day of every month

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  find:
    if: github.repository == 'nodejs/nodejs.org'
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Report inactive collaborators
        id: inactive
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { default: report } = await import("${{github.workspace}}/.github/scripts/report-inactive-collaborators.mjs");
            report(github, context);
