on:
  push:
    branches:
      - main

name: Notify on Push
permissions:
  contents: read

jobs:
  notify_on_push:
    name: Notify on any direct push to `main`
    if: >
      github.repository == 'nodejs/nodejs.org' &&
      github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: nodejs/web-team/actions/notify-on-push@74cbb4801de8068e1908b718c95f139a3f95726a
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
