name: Release and Publish

on:
  push:
    branches: [main]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.create-release.outputs.paths_released }}
      releases_created: ${{ steps.create-release.outputs.releases_created }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create release with release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: create-release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

  publish:
    name: Publish Packages
    if: needs.release.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      id-token: write # For provenance
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.release.outputs.paths_released) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Publish package with provenance
        working-directory: ${{ matrix.path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm publish --access=public --provenance
